# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Search-Image-With-Kakao-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Search-Image-With-Kakao-API
  pod 'Moya', '~> 14.0'
  pod 'Kingfisher', '~> 5.0'

  target 'Search-Image-With-Kakao-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
